version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/fudanchii/tagueuer
    steps:
      - checkout
      - run: dep ensure
      - run: go test
